#!/usr/bin/env zsh

# This script installs zprezto.
# It requires zsh to be preinstalled.

set -e

cd "${ZDOTDIR:-$HOME}"/.zprezto
git submodule update --init --recursive

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
